# Generated by Django 5.1.4 on 2025-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0df159', max_length=6),
        ),
    ]
