# Generated by Django 5.1.4 on 2025-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='password1',
            new_name='Conform_password',
        ),
        migrations.RenameField(
            model_name='signupform',
            old_name='password2',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8fbbde', max_length=6),
        ),
    ]
