# Generated by Django 5.1.4 on 2025-01-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_conform_password_signupform_conform_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgetPassword',
        ),
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='SignUpForm',
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
